### ISSUE TITLE
PR to PyMC3?

### ISSUE THREAD

**Issue by twiecki** [exoplanet-dev/pymc-ext#4]
A lot of these changes, specifically those for tuning would be a great addition to PyMC3 directly. Have you considered PRing them upstream?

**Comment by dfm** [comment]
Thanks Thomas!

I've thought about that and the `adapt_full` algorithm was developed here and [pushed upstream](https://github.com/pymc-devs/pymc3/pull/3596). I think that the current changes are experimental enough (and I'm not yet sure how much benefit they provide) that they're not ready for a PR, but I'll definitely do it when/if I have convincing evidence for some piece of this!

**Comment by dfm** [comment]
Closing because it's looking like this is going to continue to be necessary for our community alas!
